############################################################################
# Start Kubeadm
############################################################################

- name: Check if Kubeadm has already been started
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Start Kubeadm
  command: kubeadm init --feature-gates=SelfHosting=true --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ kubeadm_advertise_address|default(hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }}
  when: kubernetes_init_stat.stat.exists == False

- import_tasks: kube-conf.yml

- name: Copy Flannel configuration
  template:
    src: flannel.yml
    dest: /tmp/

- name: Create Flannel network
  command: kubectl apply -f /tmp/flannel.yml

- name: Get the kubeadm join command from master
  command: kubeadm token create --print-join-command
  changed_when: false
  register: kubernetes_join_command_result

- name: Share the kubeadm join to all other hosts
  set_fact:
    kubernetes_join_command: "{{ kubernetes_join_command_result.stdout }}"
  when: kubernetes_join_command_result.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

- name: Taint Kubeadm master
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  failed_when: false
  when: kubeadm_taint_master|default(False)|bool == True

- name: Start Dashboard
  import_tasks: start-dashboard.yml
  when: kube_dashboard|default(False)|bool == True